### ISSUE TITLE
Limit the height of aproject image on the main page

### ISSUE THREAD

**Issue by shelpuk** [szkocka/front-end#16]
Please limit the height of a project image at the main page by 600 pixels. If height is more than 600 pixels, this parameters hould be used to scale image instead of width. Image should also be centered with respect to the others in this case

**Comment by t0n** [comment]
What do you think of current implementation (attached) where it is limited in both width (100% of grid 'column') and height (crrently 200px)? Well in both width and height, it is even not _limited_, but _fixed_ to these dimensions, so image is scaled in the way it covers 100% of given area. With vertical (portait) oriented images this will lead to cropping out major part of image, but again I don't think vertical images are good to represent the project and serve as its 'cover' image.
![screen2](https://cloud.githubusercontent.com/assets/72974/14586165/5302535a-0498-11e6-9e3c-3f3a1ed6c144.png)

**Comment by t0n** [comment]
So this way all projects will have equal images, that is fair :) and also looks balanced. Height can be increased to 250-300px

**Comment by shelpuk** [comment]
Ok, looks good. If anything, we can fix this later, when we see first users uploading real project images.

You can commit this implementation and close the issue.

**Comment by t0n** [comment]
Now it is even square sized (probably Svetlana has changes it). Looks good.
