### ISSUE TITLE
when scrolling projects, align the image by the largest direction and center

### ISSUE THREAD

**Issue by shelpuk** [szkocka/front-end#18]
If the project image height is larger than width, alignment by both looks weird (see attachment).

When scrolling projects, please align project image by the largest direction (either height or width) and center it in the block.

Here is how it looks with the image: http://dustyreels.files.wordpress.com/2010/11/megamind_ver8.jpg
(See attachment)
![too-wide-screen](https://cloud.githubusercontent.com/assets/3008563/13427526/4968e5c0-dfbd-11e5-8b01-5bff458d3ca5.png)

**Comment by t0n** [comment]
I suggest to make the height fixed, and align to left side horizontally.

**Comment by shelpuk** [comment]
what if the image has width much larger than height?

**Comment by t0n** [comment]
...and add property to hide exceeding with, like trim to some max width

**Comment by shelpuk** [comment]
This scrolling is sort of a project posters. Aligning them to the left would not look good. Imagine a poster size 500x100 aligned left in this scrolling. There will be lots of white space right in the middle of the screen.

**Comment by t0n** [comment]
Tried what I though of, it looks looks like this.

I think I would try to make images with fixed size (100% width of the column, height around 200px) and it will be centered and trimmed to this dimensions. Vertically-aligned images will be heavily trimmed, only part of original image visible, but the whole list of images will look cool )
![screen-projects](https://cloud.githubusercontent.com/assets/72974/14409971/f533dac2-ff2a-11e5-81ad-73f3733ac168.png)
 anyway vertical image is not a good idea to represent the research project :)

**Comment by shelpuk** [comment]
Right, but the issue was about image in the scrolling block (see Megamind poster "No, you cannot" in the attachment of the issue).

**Comment by shelpuk** [comment]
Here is the original image:
http://dustyreels.files.wordpress.com/2010/11/megamind_ver8.jpg

**Comment by t0n** [comment]
I thought of 'when scrolling projects' = when scrolling list of projects :)

What I did with list of images is in the file attached. I think it looks good enough. Will try to do the same thing with 'scrolling' thing ('carousel' in terms of Bootstrap library components).
![screen2](https://cloud.githubusercontent.com/assets/72974/14410026/9772cb12-ff2c-11e5-9d83-4f3559edf21a.png)

**Comment by shelpuk** [comment]
Right, sorry about confusing the terminology :-)
