### ISSUE TITLE
My projects -> 'More info' issue

### ISSUE THREAD

**Issue by DagnyT** [szkocka/front-end#33]
When I load project's page from "Home" everything works fine. http://www.szkocka.org/#/project/5749328048029696/about
But when I load project's page from "My Projects" (link appears to be http://www.szkocka.org/#/project//about) (there my be some angular routing issue) I can't see any project's info Or access to forum etc. Status: ON HOLD. 
In console: 
XMLHttpRequest cannot load https://szkocka-1312.appspot.com/researches//requests. Response for preflight has invalid HTTP status code 404 
XMLHttpRequest cannot load https://szkocka-1312.appspot.com/researches/.

**Comment by sshabaranska** [comment]
Should be fixed by new architecture.
