### ISSUE TITLE
Direct http links in forums should be clickable

### ISSUE THREAD

**Issue by shelpuk** [szkocka/front-end#34]
If there is a direct link in a forum message it should be represented as a hyperlink automatically (please see screenshot).
![no_links_in_forum](https://cloud.githubusercontent.com/assets/3008563/16503636/97fd7674-3f1c-11e6-9b5d-401d21bcfef2.png)

**Comment by sshabaranska** [comment]
The only option to make it clickable is to use "Insert Hyperlink" button from the buttons bar above

**Comment by shelpuk** [comment]
No other possibilities? This affects usability greatly. Users often just copy-paste URLs without clicking the buttons.

**Comment by t0n** [comment]
While saving text on the backend, URLs could be detected via regex and framed in "Anchor" HTML elements automatically.
